version: "3.3"
services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - "/compose/database/mongo:/data/db"
    restart: always 
  prom:
    image: prom/prometheus
    restart: always 
    user: '1000'
    volumes:
      - ${PWD}/compose/database/prom/prometheus.yml:/etc/prometheus/prometheus.yml 
      - ${PWD}/compose/database/prom/data/:/prometheus/
    depends_on:
      - mongo
  grafana:
    image: grafana/grafana 
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/compose/database/grafana/data:/var/lib/grafana
    depends_on:
      - prom
      - mongo
  cvbackend:
    image: brainoom/cvmonitor:v0.3.4
    restart: always
    ports:
      - "8088:8088"
    environment:
      CVMONITOR_SAVE_BEFORE_ALIGN: ${CVMONITOR_SAVE_BEFORE_ALIGN:-'FALSE'}
      CVMONITOR_SAVE_AFTER_ALIGN: ${CVMONITOR_SAVE_AFTER_ALIGN:-'FALSE'}
      CVMONITOR_QR_TARGET_SIZE: ${CVMONITOR_QR_TARGET_SIZE:-100}
      CVMONITOR_PORT: 8088
      CVMONITOR_QR_PREFIX: ${CVMONITOR_QR_TARGET_SIZE:-""}
  backend:
    image: yehiyam/monitor-backend:v0.0.16
    restart: always
    ports:
      - "80:3000"
    expose:
      - 80
    environment:
      CVMONITOR_HOST: mongo
      DB_CONNECTION: mongodb://mongo/test
    depends_on:
      - cvbackend
      - prom
      - mongo
      - grafana
  frontend:
      image: yehiyam/frontend:v0.0.1
      restart: always
      ports:
        - "4200:4200"
      depends_on: 
        - backend