version: "3.3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.17
    restart: always
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "14250:14250"
    - "9411:9411"
    expose:
      - 16686
  mongo:
    image: mongo:4.2
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - "${PWD}/compose/database/mongo:/data/db"
  # prom:
  #   image: prom/prometheus
  #   restart: always 
  #   user: '1000'
  #   volumes:
  #     - ${PWD}/compose/database/prom/prometheus.yml:/etc/prometheus/prometheus.yml 
  #     - ${PWD}/compose/database/prom/data/:/prometheus/
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - mongo
  # grafana:
  #   image: grafana/grafana 
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ${PWD}/compose/database/grafana/data:/var/lib/grafana
  #   depends_on:
  #     - prom
  #     - mongo
  #   expose:
  #     - 3000
  cvbackend:
    image: brainoom/cvmonitor:v0.3.9
    restart: always
    ports:
      - "8088:8088"
    expose:
      - 8088
    environment:
      CVMONITOR_SPOTTIRNG_PROB_THRESHOLD: ${CVMONITOR_SPOTTIRNG_PROB_THRESHOLD:-='0.3'}
      CVMONITOR_SPOTTIRNG_MAX_SEQ_LEN: ${CVMONITOR_SPOTTIRNG_MAX_SEQ_LEN:-='10'}
      CVMONITOR_SPOTTIRNG_IOU_THRESHOLD: ${CVMONITOR_SPOTTIRNG_IOU_THRESHOLD:-='0.01'}
      CVMONITOR_SPOTTIRNG_MODEL_TYPE: ${CVMONITOR_SPOTTIRNG_MODEL_TYPE:-='FP32'}
      CVMONITOR_ORIENT_BY_EXIF: ${CVMONITOR_ORIENT_BY_EXIF:-='TRUE'}
      CVMONITOR_ORIENT_BY_QR: ${CVMONITOR_ORIENT_BY_QR:-='FALSE'}
      CVMONITOR_QR_PREFIX: ${CVMONITOR_QR_PREFIX:-='cvmonitor'}
      CVMONITOR_QR_TARGET_SIZE: ${CVMONITOR_QR_TARGET_SIZE:-=100}
      CVMONITOR_QR_BOUNDERY_SIZE: ${CVMONITOR_QR_BOUNDERY_SIZE:-=50}
      CVMONITOR_SKIP_ALIGN: ${CVMONITOR_SKIP_ALIGN:-='TRUE'}
      CVMONITOR_SAVE_BEFORE_ALIGN: ${CVMONITOR_SAVE_BEFORE_ALIGN:-='FALSE'}
      CVMONITOR_SAVE_AFTER_ALIGN: ${CVMONITOR_SAVE_AFTER_ALIGN:-='FALSE'}
      CVMONITOR_SEGMENT_THRESHOLD: ${CVMONITOR_SEGMENT_THRESHOLD:-='0.95'}
      CVMONITOR_OCR_SPOTTING: ${CVMONITOR_OCR_SPOTTING:-='TRUE'}
      CVMONITOR_OCR_THRESHOLD: ${CVMONITOR_OCR_THRESHOLD:-='0.2'}
      CVMOINTOR_QR_PDF_ROWS: ${CVMOINTOR_QR_PDF_ROWS:-=6}
      CVMOINTOR_QR_PDF_COLS: ${CVMOINTOR_QR_PDF_COLS:-=4}
      CVMONITOR_LOG_LEVEL: ${CVMONITOR_LOG_LEVEL:-='DEBUG'}
      CVMONITOR_HOST: ${CVMONITOR_HOST:-='0.0.0.0'}
      CVMONITOR_PORT: ${CVMONITOR_PORT:-='8088'}
      CVMONITOR_THRESHOLD_CHARACTER: ${CVMONITOR_THRESHOLD_CHARACTER:-='0.95'}
    depends_on: 
       - jaeger
  backend:
    image: yehiyam/monitor-backend:v0.0.18
    restart: always
    ports:
      - "80:3000"
    expose:
      - 80
    environment:
      CVMONITOR_HOST: cvbackend
      DB_CONNECTION: mongodb://mongo/test
    depends_on:
      - cvbackend
      - mongo
      - jaeger
  frontend:
      image: registry.gitlab.com/or2511/covid-frontend:setable-backend-ip 
      restart: always
      ports:
        - "4200:4200"
      expose:
        - 4200
      depends_on: 
        - backend