name: Docker Image CI

on:
  push:
    tags:
      - '*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: brainoom/cvmonitor
          tags: latest
          tag_with_ref: true

